const baseNWLWords = [
    { word: "AA", def: "rough, cindery lava" },
    { word: "AB", def: "an abdominal muscle" },
    { word: "AD", def: "an advertisement" },
    { word: "AE", def: "one (Scots)" },
    { word: "AG", def: "agriculture" },
    { word: "AH", def: "to express surprise or pleasure" },
    { word: "AI", def: "a three-toed sloth" },
    { word: "AL", def: "an East Indian tree" },
    { word: "AM", def: "present 1st person sing. of be" },
    { word: "AN", def: "indefinite article" },
    { word: "AR", def: "the letter R" },
    { word: "AS", def: "to the same degree" },
    { word: "AT", def: "in the position of" },
    { word: "AW", def: "used to express protest, disgust, or sympathy" },
    { word: "AX", def: "to work on with an ax" },
    { word: "AY", def: "an affirmative vote" },
    { word: "BA", def: "the eternal soul, in Egyptian mythology" },
    { word: "BE", def: "to have actuality" },
    { word: "BI", def: "a bisexual" },
    { word: "BO", def: "a pal" },
    { word: "BY", def: "a side issue" },
    { word: "DA", def: "a heavy Burmese knife" },
    { word: "DE", def: "of; from" },
    { word: "DO", def: "the first tone of the diatonic musical scale" },
    { word: "ED", def: "education" },
    { word: "EF", def: "the letter F" },
    { word: "EH", def: "to express doubt or surprise" },
    { word: "EL", def: "an elevated railroad or train" },
    { word: "EM", def: "the letter M" },
    { word: "EN", def: "the letter N" },
    { word: "ER", def: "used to express hesitation" },
    { word: "ES", def: "the letter S" },
    { word: "ET", def: "a past tense of eat" },
    { word: "EW", def: "used to express disgust" },
    { word: "EX", def: "the letter X" },
    { word: "FA", def: "the fourth tone of the diatonic musical scale" },
    { word: "FE", def: "a Hebrew letter" },
    { word: "GI", def: "a white garment worn in martial arts" },
    { word: "GO", def: "to move along" },
    { word: "HA", def: "a sound of surprise or triumph" },
    { word: "HE", def: "a male person" },
    { word: "HI", def: "used as a greeting" },
    { word: "HM", def: "used to express hesitation" },
    { word: "HO", def: "to express surprise" },
    { word: "ID", def: "a part of the psyche" },
    { word: "IF", def: "a possibility" },
    { word: "IN", def: "to harvest" },
    { word: "IS", def: "present 3d person sing. of be" },
    { word: "IT", def: "the 3d person sing. neuter pronoun" },
    { word: "JO", def: "a sweetheart" },
    { word: "KA", def: "the spiritual self of a human being in Egyptian religion" },
    { word: "KI", def: "the vital force in Chinese thought" },
    { word: "LA", def: "the sixth tone of the diatonic musical scale" },
    { word: "LI", def: "a Chinese unit of distance" },
    { word: "LO", def: "used to attract attention or to express surprise" },
    { word: "MA", def: "a mother" },
    { word: "ME", def: "the objective case of the pronoun I" },
    { word: "MI", def: "the third tone of the diatonic musical scale" },
    { word: "MM", def: "used to express assent or satisfaction" },
    { word: "MO", def: "a moment" },
    { word: "MU", def: "a Greek letter" },
    { word: "MY", def: "the possessive form of the pronoun I" },
    { word: "NA", def: "no; not" },
    { word: "NE", def: "born with the name of" },
    { word: "NO", def: "a negative reply" },
    { word: "NU", def: "a Greek letter" },
    { word: "OD", def: "a hypothetical force of natural power" },
    { word: "OE", def: "a whirlwind off the Faeroe islands" },
    { word: "OF", def: "coming from" },
    { word: "OH", def: "to exclaim in surprise" },
    { word: "OI", def: "a working-class greeting" },
    { word: "OK", def: "to approve" },
    { word: "OM", def: "a mantra used in contemplation of ultimate reality" },
    { word: "ON", def: "the side of the wicket where a batsman stands" },
    { word: "OP", def: "a style of abstract art" },
    { word: "OR", def: "the heraldic color gold" },
    { word: "OS", def: "a bone" },
    { word: "OW", def: "used to express sudden pain" },
    { word: "OX", def: "a clumsy person" },
    { word: "OY", def: "used to express dismay or pain" },
    { word: "PA", def: "a father" },
    { word: "PE", def: "a Hebrew letter" },
    { word: "PI", def: "a Greek letter" },
    { word: "PO", def: "a chamber pot" },
    { word: "QI", def: "the vital force that in Chinese thought is inherent in all things" },
    { word: "RE", def: "the second tone of the diatonic musical scale" },
    { word: "SH", def: "used to urge silence" },
    { word: "SI", def: "ti (a musical tone)" },
    { word: "SO", def: "the fifth tone of the diatonic musical scale" },
    { word: "TA", def: "an expression of gratitude" },
    { word: "TE", def: "ti (a musical tone)" },
    { word: "TI", def: "the seventh tone of the diatonic musical scale" },
    { word: "TO", def: "in the direction of" },
    { word: "UH", def: "used to express hesitation" },
    { word: "UM", def: "used to express hesitation" },
    { word: "UN", def: "one" },
    { word: "UP", def: "to raise" },
    { word: "US", def: "the objective case of the pronoun we" },
    { word: "UT", def: "the musical tone C in the French solmization system" },
    { word: "WE", def: "1st person pl. pronoun in the nominative case" },
    { word: "WO", def: "woe" },
    { word: "XI", def: "a Greek letter" },
    { word: "XU", def: "a monetary unit of Vietnam" },
    { word: "YA", def: "an Asian pear" },
    { word: "YE", def: "you" },
    { word: "YO", def: "used to call attention or to express affirmation" },
    { word: "ZA", def: "a pizza" }
];

const cswOnlyWords = [
    { word: "CH", def: "an English dialect word for I" },
    { word: "DI", def: "a plural of deus (god)" },
    { word: "EA", def: "a river (dialect)" },
    { word: "EE", def: "an eye (Scots)" },
    { word: "FY", def: "an interjection expressing disgust" },
    { word: "GU", def: "a simple violin used in Shetland" },
    { word: "IO", def: "a moth with a large spot on each hind wing" },
    { word: "JA", def: "yes" },
    { word: "KO", def: "a Maori digging implement" },
    { word: "KY", def: "cows (Scots)" },
    { word: "NY", def: "to approach (Scots)" },
    { word: "OB", def: "an objection" },
    { word: "OO", def: "wool (Scots)" },
    { word: "OU", def: "a man, a bloke (South African)" },
    { word: "ST", def: "used to attract attention or urge silence" },
    { word: "UG", def: "to arouse disgust in" },
    { word: "UR", def: "expressing hesitation" },
    { word: "YU", def: "a precious jade" },
    { word: "ZE", def: "a gender-neutral pronoun" },
    { word: "ZO", def: "a Tibetan yak" }
];

const baseFakeWords = [
    "RA", "CA", "GA", "SA", "VA", "WA", "QA", "XA", 
    "CE", "GE", "JE", "KE", "LE", "QE", "SE", "VE", "XE",
    "CI", "FI", "JI", "NI", "RI", "VI", "WI", "ZI", "YI",
    "CO", "FO", "QO", "RO", "VO", "XO",
    "BU", "CU", "DU", "FU", "HU", "JU", "KU", "LU", "PU", "QU", "RU", "SU", "TU", "VU", "WU", "ZU",
    "AC", "AF", "AK", "AP", "AQ", "AV", "AZ",
    "EB", "EC", "EG", "EK", "EP", "EQ", "EV", "EZ",
    "IB", "IC", "IG", "IK", "IL", "IM", "IP", "IQ", "IR", "IV", "IX", "IZ",
    "OC", "OG", "OL", "OQ", "OT", "OV", "OZ",
    "UB", "UC", "UD", "UF", "UK", "UL", "UQ", "UV", "UX", "UZ"
];
